### ISSUE TITLE
Unexpected output data

### ISSUE THREAD

**Issue by abdikanipd** [napalm-automation-community/napalm-huawei-vrp#28]
Facing issue: Unexpected output data: [" ^\nError: Unrecognized command found at '^' position."] I hope issue is my device have super mode password, passed secret optional value still facing same issue

**Comment by codingnetworksb** [comment]
Hi @abdikanipd, could please elaborate more? How can reproduce this error? Please share code and device.

**Comment by abdikanipd** [comment]
@codingnetworksb thanks <html>
<body>

failed | fail-general | Unexpected output data: ["^\nError: Unrecognized command found at '^' position."]

Getting this issue one I try to import this device to nautobot Onboarding, also I get another issue ^ Error: Unrecognized command found at '^' position. when try to get running configuration on device.      Device type HUAWEI S6330-H48X6C 

</body>
</html>

**Comment by codingnetworksb** [comment]
Hi @abdikanipd ,
Sorry i don't recognize this error. Since i don't support Nautobot, i don't know if the error is triggered by any incompatibility napalm-huawei-vrp and Naurobot.

I suggest you open a issue in Naurobot project, so they can help to determine the root cause of the error. If they share specific details of the cause and find out that it is a napalm-huawei-vrp issue, feel free to come back share me the link to the issue, so we can work on the solution.
